# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - ./node_modules
    - ./repo

before_script:
  - mkdir out
  - git clone https://github.com/EssentialsX/Essentials repo
  - cd repo
  - git pull
  - cd ..

run_items:
  script:
    - yarn
    - node ./src/genItemsFlat.js
    - node ./test/itemsCoverage.js
  artifacts:
    paths:
      - out/items.json
      - out/items.report.json

run_locale:
  image: python:3.7
  script:
    - cd repo/Essentials/src
    - python ../../../python/localeReport.py > ../../../out/locale.report.md
  artifacts:
    paths:
      - out/locale.report.md
