# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - ./node_modules
  
before_script:
  - mkdir out

run_items:
  script:
    - yarn
    - node ./src/genItemsFlat.js
    - node ./test/itemsCoverage.js
  artifacts:
    paths:
      - out/items.json
      - out/items.report.json
